<a href="https://colab.research.google.com/github/rukaiyafahmida/AI-Project/blob/main/170204004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Libraries

In [172]:
#load libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
%matplotlib inline

import os
#print(os.listdir("https://raw.githubusercontent.com/rukaiyafahmida/AI-Project/main/pulsar_data_train.csv"))

from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

# Load Data

In [173]:
df = pd.read_csv("https://raw.githubusercontent.com/rukaiyafahmida/AI-Project/main/dataset.csv")

In [174]:
df.head()

Mean of the integrated profile  ...  Class
0                       90.132812  ...      0
1                       80.281250  ...      0
2                       94.664062  ...      0
3                       91.773438  ...      1
4                      111.898438  ...      0

[5 rows x 9 columns]

# Data Cleaning And Chceking

In [175]:
#let's check for missing/ unique values
def dfaux (df):
    cant = df.isnull().sum()
    df_aux = pd.DataFrame(index = df.columns, data =
                         {'type': df.dtypes,
                          'unique_values': df.nunique(),
                          'have_null?': df.isnull().any(),
                          'how many?' : cant,
                          'per' : cant/df.shape[0]*100 })
    return df_aux

In [176]:
dfaux(df)

type  ...  per
Mean of the integrated profile                float64  ...  0.0
Standard deviation of the integrated profile  float64  ...  0.0
Excess kurtosis of the integrated profile     float64  ...  0.0
Skewness of the integrated profile            float64  ...  0.0
Mean of the DM-SNR curve                      float64  ...  0.0
Standard deviation of the DM-SNR curve        float64  ...  0.0
Excess kurtosis of the DM-SNR curve           float64  ...  0.0
Skewness of the DM-SNR curve                  float64  ...  0.0
Class                                           int64  ...  0.0

[9 rows x 5 columns]

In [177]:
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'Class'],
      dtype='object')

# Analysing Dataset

In [ ]:
df.shape

614 -> rows

9 -> columns(features)

In [ ]:
df.info()

All the features are of float type, except the target class

In [ ]:
df.describe()

The mean of the target variable is about 15.0%, hence we can say that only 15.0% stars are pulsar stars 

In [185]:
#feature scaling
features = df.drop("Class", axis=1)
scaler = MinMaxScaler(feature_range=(0,1))
fscaled = scaler.fit_transform(features)

# Modeling

In [186]:
#separating input and target variable
X = df.drop("Class", axis=1)
Y = df["Class"]

In [187]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state = 4 )

# Logistic Regression

In [217]:
#1. Logistic Regression
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
y_pred1 = logreg.predict(x_test)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


# Confusion Matrix Of Logistic Regression

In [218]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred1 = logreg.predict(x_test)
cm = confusion_matrix(y_test, y_pred1)
print(cm)

[[130   1]
 [  5  18]]


# Accuracy Of Logistic Regression

In [226]:

acc_lr = round(accuracy_score(y_test , y_pred1) * 100, 3)
print('Accuracy: %.3f' % acc_lr)

Accuracy: 96.104


# F1 Score Of Logistic Regression

In [227]:
from sklearn.metrics import f1_score
f1_LR = f1_score(y_test, y_pred1, zero_division=1)*100
print('F1 score: %.2f' % f1_LR)

F1 score: 85.71


# Recall Score Of Logistic Regression

In [228]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred1)*100
print("Recall: %.2f" % recall)

Recall: 78.26


# Precision score  Of Logistic Regression




In [229]:
from sklearn.metrics import precision_score
precision =  precision_score(y_test, y_pred1)*100
print('precision: %.2f' % precision)

precision: 94.74


# KNN

In [194]:
#2. KNN
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)
y_pred2 = knn.predict(x_test)

# Confusion Matrix Of KNN

In [195]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred2)
print(cm)

[[129   2]
 [  6  17]]


# Accuracy Of KNN

In [230]:

acc = round(accuracy_score(y_test , y_pred2) * 100, 3)
print('Accuracy: %.3f' % acc)

Accuracy: 94.805


# F1 Score Of KNN

In [231]:
from sklearn.metrics import f1_score
f1_LR = f1_score(y_test, y_pred2, zero_division=1)*100
print('F1 score: %.2f' % f1_LR)

F1 score: 80.95


# Recall Score Of KNN

In [232]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred2)*100
print("Recall: %.2f" % recall)

Recall: 73.91


# Precision score  Of KNN




In [233]:
from sklearn.metrics import precision_score
precision =  precision_score(y_test, y_pred2)*100
print('precision: %.2f' % precision)

precision: 89.47


# Gaussian Naive Bayers

In [214]:
#3. GNB
gauss = GaussianNB()
gauss.fit(x_train, y_train)
y_pred3 = gauss.predict(x_test)

# Confusion Matrix Of Gaussian Naive Bayers

In [215]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred3)
print(cm)

[[129   2]
 [  3  20]]


# Accuracy Of Gaussian Naive Bayers

In [216]:

acc = round(accuracy_score(y_test , y_pred3) * 100, 3)
print('Accuracy: %.3f' % acc)

Accuracy: 96.753


# F1 Score Of Gaussian Naive Bayers

In [234]:
from sklearn.metrics import f1_score
f1_LR = f1_score(y_test, y_pred3, zero_division=1)*100
print('F1 score: %.2f' % f1_LR)

F1 score: 88.89


# Recall Score Of Gaussian Naive Bayers

In [236]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred3)*100
print("Recall: %.2f" % recall)

Recall: 86.96


# Precision score  Of Gaussian Naive Bayers




In [237]:
from sklearn.metrics import precision_score
precision =  precision_score(y_test, y_pred3)*100
print('precision: %.2f' % precision)

precision: 90.91
